version: '2'

services:
  apollo-configservice:
    container_name: apollo-configservice
    build: F:/Software/Git/Git/apollo-config/apollo-config/apollo-configservice/src/main/docker
    image: docker.registry:30018/godeye/apollo-configservice:0.11.0
    ports: 
      - "8080:8768"
    volumes:
      - "/Users/modin/opt/logs/100003171:/opt/logs/100003171"
    environment:
      - spring_datasource_url=jdbc:mysql://rm-2ze5w706ah6050ie8ko.mysql.rds.aliyuncs.com/apollo_config_dev?useSSL=false
      - spring_datasource_username=root
      - spring_datasource_password=tVFaeamXfvo9kwK

  apollo-adminservice:
    container_name: apollo-adminservice
    build: F:/Software/Git/Git/apollo-config/apollo-config/apollo-adminservice/src/main/docker/
    image: docker.registry:30018/godeye/apollo-adminservice:0.11.0
    ports:
      - "8090:8767"
    depends_on:
      - apollo-configservice
    volumes:
      - "/Users/mobin/opt/logs/100003172:/opt/logs/100003172"
    environment:
      - spring_datasource_url=jdbc:mysql://rm-2ze5w706ah6050ie8ko.mysql.rds.aliyuncs.com/apollo_config_dev?useSSL=false
      - spring_datasource_username=root
      - spring_datasource_password=tVFaeamXfvo9kwK

  apollo-portal:
    container_name: apollo-portal
    build: F:/Software/Git/Git/apollo-config/apollo-config/apollo-portal/src/main/docker/
    image: docker.registry:30018/godeye/apollo-portal:0.11.0
    ports:
      - "8070:8766"
    depends_on:
      - apollo-adminservice
    volumes:
      - "/Users/mobin/opt/logs/100003173:/opt/logs/100003173"
    environment:
      - spring_datasource_url=jdbc:mysql://rm-2ze5w706ah6050ie8ko.mysql.rds.aliyuncs.com/apollo_portal?useSSL=false
      - spring_datasource_username=root
      - spring_datasource_password=tVFaeamXfvo9kwK
