spring:
  application:
    name: apollo-adminservice
  profiles:
    active: dev
  cloud:
    inetutils:
      ignored-interfaces:
      - docker0
      - veth.*
ctrip:
  appid: 100003172
  
server:
  port: 8767
  
logging:
  file: /logs/apollo-adminservice.log
