spring:
  application:
    name: apollo-adminservice
    
server:
  port: ${port:23646}
  
logging:
  level:
    org.springframework.cloud: 'DEBUG'
  file: /opt/logs/apollo-adminservice.log

ctrip:
  appid: 100003172
