spring:
  ldap:
    base: "OU=tuhu-users,DC=tuhu,DC=ad"
    username: "gitlab" # 配置管理员账号，用于搜索、匹配用户
    password: "z6rFvKk56S2018"
    searchFilter: "(sAMAccountName={0})"  # 用户过滤器，登录的时候用这个过滤器来搜索用户
    urls:
    - "ldap://172.16.10.1:389"
    - "ldap://172.16.10.2:389"

ldap:
  mapping: # 配置 ldap 属性
    objectClass: "user" # ldap 用户 objectClass 配置
    loginId: "sAMAccountName" # ldap 用户惟一 id，用来作为登录的 id
    userDisplayName: "cn" # ldap 用户名，用来作为显示名
    email: "userPrincipalName" # ldap 邮箱属性
  #filter: # 可选项，配置过滤，目前只支持 memberOf
    #memberOf: "CN=ServiceDEV,OU=test,DC=example,DC=com|CN=WebDEV,OU=test,DC=example,DC=com" # 只允许 memberOf 属性为 ServiceDEV 和 WebDEV 的用户访问
