spring:
  application:
    name: apollo-configservice
  profiles:
    active: dev
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*

ctrip:
  appid: 100003171
  
server:
  port: 8768
  
logging:
  file: /logs/apollo-configservice.log
