spring:
  application:
    name: apollo-configservice

server:
  port: ${port:2756}
  
logging:
  level:
    org.springframework.cloud: 'DEBUG'
  file: /opt/logs/apollo-configservice.log

ctrip:
  appid: 100003171