server:
  port: 8080
  
spring:
  application:
    name: apollo-portal
  datasource:
    url: jdbc:h2:mem:~/fxapolloportaldb
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

logging:
  level:
    org.springframework.cloud: 'DEBUG'
  file: /opt/logs/${ctrip.appid}/apollo-adminservice.log
  
ctrip:
  appid: 100003173
