server:
  port: 8070
  
spring:
  application:
    name: apollo-portal

logging:
  level:
    org.springframework.cloud: 'DEBUG'
  file: /opt/logs/${ctrip.appid}/apollo-portal.log
  
ctrip:
  appid: 100003173
  
apollo:
  portal:
    env: local
