spring:
  application:
    name: apollo-portal
  profiles:
    active: github,auth
  resources:
    cache-period: 3600

server:
  port: 8766
  
logging:
  file: /logs/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


